/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppConnectionDialog: typeof import('./src/components/AppConnectionDialog.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppSystemBar: typeof import('./src/components/AppSystemBar.vue')['default']
    AppTooltip: typeof import('./src/components/AppTooltip.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
